### ISSUE TITLE
Address TODOs to bring back the metric global package

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#2752]
Blocked by https://github.com/open-telemetry/opentelemetry-go/pull/2750 which adds back the `Meter` function.

## TODOs

- [ ] https://github.com/open-telemetry/opentelemetry-go/blob/bbcdc75ede428d61212caee9222d68300b7e70a7/sdk/metric/benchmark_test.go#L184-L204
- [ ] https://github.com/open-telemetry/opentelemetry-go/blob/bbcdc75ede428d61212caee9222d68300b7e70a7/exporters/otlp/otlpmetric/otlpmetricgrpc/example_test.go#L56-L57
- [ ] https://github.com/open-telemetry/opentelemetry-go/blob/bbcdc75ede428d61212caee9222d68300b7e70a7/exporters/otlp/otlpmetric/otlpmetricgrpc/example_test.go#L71-L72
- [ ] https://github.com/open-telemetry/opentelemetry-go/blob/bbcdc75ede428d61212caee9222d68300b7e70a7/exporters/otlp/otlpmetric/otlpmetricgrpc/example_test.go#L118-L119
- [ ] https://github.com/open-telemetry/opentelemetry-go/blob/bbcdc75ede428d61212caee9222d68300b7e70a7/exporters/otlp/otlpmetric/otlpmetricgrpc/example_test.go#L134-L135
- [ ] https://github.com/open-telemetry/opentelemetry-go/blob/bbcdc75ede428d61212caee9222d68300b7e70a7/exporters/otlp/otlpmetric/otlpmetricgrpc/example_test.go#L177-L178
- [ ] https://github.com/open-telemetry/opentelemetry-go/blob/bbcdc75ede428d61212caee9222d68300b7e70a7/exporters/otlp/otlpmetric/otlpmetricgrpc/example_test.go#L192-L193
- [ ] https://github.com/open-telemetry/opentelemetry-go/blob/bbcdc75ede428d61212caee9222d68300b7e70a7/exporters/stdout/stdoutmetric/example_test.go#L36-L40
- [ ] https://github.com/open-telemetry/opentelemetry-go/blob/bbcdc75ede428d61212caee9222d68300b7e70a7/exporters/stdout/stdoutmetric/example_test.go#L85-L86
- [ ] https://github.com/open-telemetry/opentelemetry-go/blob/bbcdc75ede428d61212caee9222d68300b7e70a7/exporters/stdout/stdoutmetric/example_test.go#L108
- [ ] https://github.com/open-telemetry/opentelemetry-go/blob/bbcdc75ede428d61212caee9222d68300b7e70a7/example/prometheus/main.go#L39
- [ ] https://github.com/open-telemetry/opentelemetry-go/blob/bbcdc75ede428d61212caee9222d68300b7e70a7/example/prometheus/main.go#L60-L61
- [ ] https://github.com/open-telemetry/opentelemetry-go/blob/bbcdc75ede428d61212caee9222d68300b7e70a7/example/prometheus/main.go#L75-L76

**Comment by bradtopol** [comment]
Hi @MrAlias. As you mentioned in the weekly meeting, I am willing to look at handling this issue. I will contact you about it on slack.
