### ISSUE TITLE
Release v1.7.0 Checklist

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#2861]
- [x] Complete [Milestone](https://github.com/open-telemetry/opentelemetry-go/milestone/20)
- [x] Update contrib codebase to support changes about to be released (use a git sha version)
  - [x] https://github.com/open-telemetry/opentelemetry-go-contrib/pull/2222
  - [x] https://github.com/open-telemetry/opentelemetry-go-contrib/pull/2224
- [x] [Pre-release](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#pre-release)
  - https://github.com/open-telemetry/opentelemetry-go/pull/2869
- [x] [Tag](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#tag)
- [x] [Release](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#release)
  - https://github.com/open-telemetry/opentelemetry-go/releases/tag/v1.7.0
- [x] [Check examples](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#verify-examples)
- [x] [Sync with Contrib](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/RELEASING.md#upgrade-goopentelemetryiootel-packages)
  - https://github.com/open-telemetry/opentelemetry-go-contrib/pull/2255
- [x] [Release contrib](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/RELEASING.md#release-process)
  - https://github.com/open-telemetry/opentelemetry-go-contrib/releases/tag/v1.7.0
- [x] [Sync website docs](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#website-documentation)
  - https://github.com/open-telemetry/opentelemetry.io/pull/1323
- [x] Close the milestone

**Comment by MrAlias** [comment]
Blocked by https://github.com/open-telemetry/opentelemetry-go-contrib/pull/2222 and https://github.com/open-telemetry/opentelemetry-go-contrib/pull/2224
