### ISSUE TITLE
Support exponential histograms

### ISSUE THREAD

**Issue by MadVikingGod** [open-telemetry/opentelemetry-go#2966]
The new metric SDK should support exponential histograms.

This would require a way to select them as an aggregation, and the data type in the export path.

The plan as it currently stands is:

- [x] Support Exponential Histograms in metricdata package (#4165)
- [x] Support Exponential Histograms in exporters (#4222)
- [ ] Create an Exponential Histograms internal.Aggregation(#4245)

**Comment by MadVikingGod** [comment]
This will have a number of subtasks:

- [ ] Support expo in metricdata package
- [ ] Support ExpoHisto in exporters
- [ ] Create an ExpoHisto internal.Aggregation

**Comment by MrAlias** [comment]
Discussed in the SIG meeting today: this might better fit in the post-GA metric SDK project. It needs to be verified that this can be added in a backwards compatible manner. If so, work to add it should be postponed until the specification has stabilized this section.

**Comment by MrAlias** [comment]
Moving to the Metric SDK (GA) project. This needs to be included in the stable release of the SDK as it is a recommended aggregation of the specification.
