### ISSUE TITLE
Release <V1.10.0> Checklist

### ISSUE THREAD

**Issue by MadVikingGod** [open-telemetry/opentelemetry-go#3157]
- [x] Complete [Milestone](https://github.com/open-telemetry/opentelemetry-go/milestone/26)

- [x] Update contrib codebase to support changes about to be released (use a git sha version)
- [x] [Pre-release](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#pre-release) ( #3158 )
- [x] [Tag](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#tag)
- [x] [Release](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#release)
- [x] [Check examples](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#verify-examples)
- [x] [Sync with Contrib](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/RELEASING.md#upgrade-goopentelemetryiootel-packages) (https://github.com/open-telemetry/opentelemetry-go-contrib/pull/2752)
- [x] [Release contrib](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/RELEASING.md#release-process)
- [x] [Sync website docs](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#website-documentation)
- [x] Close the milestone
