### ISSUE TITLE
Release v0.32.0 -- Revised Metric SDK (Alpha) Checklist

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#3176]
- [x] Complete [metric alpha SDK milestone](https://github.com/open-telemetry/opentelemetry-go/milestone/22)

- [x] Update contrib codebase to support changes about to be released (use a git sha version)
   - https://github.com/open-telemetry/opentelemetry-go-contrib/pull/2754
   - https://github.com/open-telemetry/opentelemetry-go-contrib/pull/2756
   - https://github.com/open-telemetry/opentelemetry-go-contrib/pull/2758
   - https://github.com/open-telemetry/opentelemetry-go-contrib/pull/2760
   - https://github.com/open-telemetry/opentelemetry-go-contrib/pull/2762
- [x] [Pre-release](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#pre-release)
- [x] [Tag](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#tag)
- [x] [Release](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#release)
- [x] [Check examples](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#verify-examples)
- [x] [Sync with Contrib](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/RELEASING.md#upgrade-goopentelemetryiootel-packages)
- [x] [Release contrib](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/RELEASING.md#release-process)
- [x] [Sync website docs](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#website-documentation)
   - https://github.com/open-telemetry/opentelemetry.io/pull/1771
- [x] Close the [release milestone](https://github.com/open-telemetry/opentelemetry-go/milestone/28)

**Comment by MrAlias** [comment]
Done
