### ISSUE TITLE
Release v0.32.0 -- OpenCensus Bridge Checklist

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#3204]
Release the updated OpenCensus bridge from #3192. This is used as a temporary solution for users while #2808 is being worked on.

- [ ] Update contrib codebase to support changes about to be released (use a git sha version)
- [ ] [Pre-release](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#pre-release)
- [ ] [Tag](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#tag)
- [ ] [Release](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#release)
- [ ] [Check examples](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#verify-examples)
- [ ] [Sync with Contrib](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/RELEASING.md#upgrade-goopentelemetryiootel-packages)
- [ ] [Release contrib](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/RELEASING.md#release-process)
