### ISSUE TITLE
Release v1.11.0/v0.32.3 Checklist

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#3274]
A complete release is needed to address https://github.com/open-telemetry/opentelemetry-go/issues/3272

- [x] [Pre-release](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#pre-release)
- [x] [Tag](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#tag)
- [x] [Release](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#release)
- [x] [Check examples](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#verify-examples)
- [x] [Sync with Contrib](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/RELEASING.md#upgrade-goopentelemetryiootel-packages)
- [x] [Release contrib](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/RELEASING.md#release-process)

**Comment by MrAlias** [comment]
https://github.com/open-telemetry/opentelemetry-go/pull/3275

**Comment by MrAlias** [comment]
https://github.com/open-telemetry/opentelemetry-go-contrib/pull/2859
