### ISSUE TITLE
Release v1.11.1/v0.33.0 Checklist

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#3366]
- [x] Complete milestones
   - [x] https://github.com/open-telemetry/opentelemetry-go/milestone/31
   - [x] https://github.com/open-telemetry/opentelemetry-go/milestone/32
- [x] Update contrib codebase to support changes about to be released (use a git sha version)
- [x] [Pre-release](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#pre-release): https://github.com/open-telemetry/opentelemetry-go/pull/3367
- [x] [Tag](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#tag)
- [x] [Release](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#release)
- [x] [Check examples](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#verify-examples)
- [x] [Sync with Contrib](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/RELEASING.md#upgrade-goopentelemetryiootel-packages)
- [x] [Release contrib](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/RELEASING.md#release-process): https://github.com/open-telemetry/opentelemetry-go-contrib/pull/2875
- [x] [Sync website docs](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#website-documentation): https://github.com/open-telemetry/opentelemetry.io/pull/1882
- [x] Close the milestones

**Comment by MrAlias** [comment]
https://github.com/open-telemetry/opentelemetry-go/pull/3367
