### ISSUE TITLE
Release v1.12.0/v0.35.0 Checklist

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#3622]
- Complete milestones
  - [x] [Release v1.12.0](https://github.com/open-telemetry/opentelemetry-go/milestone/35)
  - [x] [Metric v0.35.0](https://github.com/open-telemetry/opentelemetry-go/milestone/36)
- Update contrib codebase to support changes about to be released (use a git sha version)
  - [x] https://github.com/open-telemetry/opentelemetry-go-contrib/pull/3170
  - [x] https://github.com/open-telemetry/opentelemetry-go-contrib/pull/3182
- [x] [Pre-release](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#pre-release): https://github.com/open-telemetry/opentelemetry-go/pull/3623
- [x] [Tag](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#tag)
- [x] [Release](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#release): https://github.com/open-telemetry/opentelemetry-go/releases/tag/v1.12.0
- [x] [Check examples](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#verify-examples)
- [x] [Sync with Contrib](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/RELEASING.md#upgrade-goopentelemetryiootel-packages)
- [x] [Release contrib](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/RELEASING.md#release-process)
- [x] [Sync website docs](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#website-documentation): https://github.com/open-telemetry/opentelemetry.io/pull/2229
- [x] Close the milestones
