### ISSUE TITLE
Release v1.14.0/v0.37.0/v0.0.4 Checklist

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#3809]
- [x] Complete milestones
  - [v1.14.0](https://github.com/open-telemetry/opentelemetry-go/milestone/39)
  - [Metric v0.37.0](https://github.com/open-telemetry/opentelemetry-go/milestone/40)
  - [Schema v0.0.4](https://github.com/open-telemetry/opentelemetry-go/milestone/41)
- [x] Update contrib codebase to support changes about to be released (use a git sha version)
- [x] [Pre-release](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#pre-release)
- [x] [Tag](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#tag)
- [x] [Release](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#release)
- [x] [Check examples](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#verify-examples)
- [x] [Sync with Contrib](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/RELEASING.md#upgrade-goopentelemetryiootel-packages)
- [x] [Release contrib](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/RELEASING.md#release-process)
- [x] [Sync website docs](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#website-documentation)
- [x] Close the milestone

**Comment by MrAlias** [comment]
My plan right after this release is to make another release: v1.15.0-RC1

This release will include:

- The metric API packages with the stable-v1 modules.
- The functionality of `otel/metric/global` being added to `otel`.
- The `otel/metric/global` package being deprecated.

Having the shuffle of the global package means the stable modules will be blocked for their release.

The reason to not release the stable modules with the metric API in an RC right now is that there are features in the stable modules ready to be released now.

**Comment by MrAlias** [comment]
https://github.com/open-telemetry/opentelemetry-go-contrib/pull/3509

**Comment by MrAlias** [comment]
done
