### ISSUE TITLE
Release v1.15.0/v0.38.0 Checklist

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#4025]
- [x] Complete milestones:
   - [x] [v1.15.0](https://github.com/open-telemetry/opentelemetry-go/milestone/44)
   - [x] [Metric v0.38.0](https://github.com/open-telemetry/opentelemetry-go/milestone/43)
- [x] Update contrib codebase to support changes about to be released (use a git sha version)
   - https://github.com/open-telemetry/opentelemetry-go-contrib/pull/3744
- [x] [Pre-release](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#pre-release)
   - https://github.com/open-telemetry/opentelemetry-go/pull/4035
- [x] [Tag](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#tag)
- [x] [Release](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#release)
- [x] [Check examples](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#verify-examples)
- [x] [Sync with Contrib](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/RELEASING.md#upgrade-goopentelemetryiootel-packages)
   - https://github.com/open-telemetry/opentelemetry-go-contrib/pull/3745
- [x] [Release contrib](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/RELEASING.md#release-process)
- [x] [Sync website docs](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#website-documentation)
- [x] Close the milestone

**Comment by MrAlias** [comment]
complete
