### ISSUE TITLE
Release v1.16.0 (Stable Metric API) Checklist

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#4099]
- [x] Complete [Milestone](https://github.com/open-telemetry/opentelemetry-go/milestone/46)
- [x] Update contrib codebase to support changes about to be released (use a git sha version)
- [x] [Pre-release](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#pre-release)
  - https://github.com/open-telemetry/opentelemetry-go/pull/4100
- [x] [Tag](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#tag)
- [x] [Release](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#release)
- [x] [Check examples](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#verify-examples)
- [x] [Sync with Contrib](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/RELEASING.md#upgrade-goopentelemetryiootel-packages)
  - https://github.com/open-telemetry/opentelemetry-go-contrib/pull/3874
- [x] [Release contrib](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/RELEASING.md#release-process)
- [x] [Sync website docs](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#website-documentation)
- [x] Close the milestone

**Comment by MrAlias** [comment]
done

**Comment by JobberRT** [comment]
Sorry if it's not the right place to comment:

1. [website-doc](https://opentelemetry.io/docs/instrumentation/go/) `Status and Releases
` part, the metrics api is still **Beta** when `Readme` has updated to `Stable`
2. will metrics api have a full example that has a full progress from `SetXXXProvider` to `NewXXXExporter` like `website-doc` Getting Started example?

**Comment by MrAlias** [comment]
> 1. [website-doc](https://opentelemetry.io/docs/instrumentation/go/) `Status and Releases ` part, the metrics api is still **Beta** when `Readme` has updated to `Stable`

The SDK has not been released as stable yet. Since there is not distinction in that table to make this point I think leaving it as it is is best.

> will metrics api have a full example that has a full progress from `SetXXXProvider` to `NewXXXExporter` like `website-doc` Getting Started example?

That sounds reasonable. Please create a new separate issue for the request so we can track that work there.
