### ISSUE TITLE
Release v1.26.0 Checklist

### ISSUE THREAD

**Issue by XSAM** [open-telemetry/opentelemetry-go#5250]
- [x] Complete [Milestone](https://github.com/open-telemetry/opentelemetry-go/milestone/58)

- [x] Update contrib codebase to support changes about to be released (use a git sha version)
- [x] [Pre-release](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#pre-release): #5260
- [x] [Tag](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#tag)
- [x] [Release](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#release)
- [x] [Check examples](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#verify-examples)
- [x] [Sync with Contrib](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/RELEASING.md#upgrade-goopentelemetryiootel-packages) https://github.com/open-telemetry/opentelemetry-go-contrib/pull/5426
- [x] [Release contrib](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/RELEASING.md#release-process)
- [x] Close the milestone

**Comment by MrAlias** [comment]
@XSAM I'm going to start the release of contrib. Please let me know if you are already working on it.

**Comment by MrAlias** [comment]
Complete
