### ISSUE TITLE
Release v1.29.0 Checklist

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#5731]
- Complete milestones:
  - [x] https://github.com/open-telemetry/opentelemetry-go-contrib/milestone/22
  - [x] https://github.com/open-telemetry/opentelemetry-go/milestone/61
- [x] [Update contrib codebase to support changes about to be released (use a git sha version)](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#verify-changes-for-contrib-repository)
- [x] [Pre-release](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#pre-release): https://github.com/open-telemetry/opentelemetry-go/pull/5732
- [x] [Tag](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#tag)
- [x] [Release](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#release)
- [x] [Check examples](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#verify-examples)
- [x] [Sync with Contrib](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/RELEASING.md#upgrade-goopentelemetryiootel-packages)
- [x] [Release contrib](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/RELEASING.md#release-process): https://github.com/open-telemetry/opentelemetry-go-contrib/pull/6042
- [x] [Sync website docs](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#website-documentation)
- [x] Close the milestones

**Comment by MrAlias** [comment]
Done
